name: Frontend CI

# Trigger the workflow on pull requests and allow manual runs
on:
  pull_request:
  workflow_dispatch:

jobs:
  # Lint job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 to support Node.js 16/20

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Ensure using the correct version
        with:
          node-version: '20'  # Use Node.js 20 as the latest stable version

      - name: Cache Node.js modules
        uses: actions/cache@v3  # Updated to v3 for Node.js 16/20 compatibility
        with:
          path: starter/frontend/node_modules  # Adjusted path to reflect the correct directory
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend  # Set working-directory to the "starter/frontend" folder

      - name: Run prettier to fix formatting
        run: npx prettier --check .
        working-directory: ./starter/frontend

      - name: Run lint
        run: npm run lint
        working-directory: ./starter/frontend  # Set working-directory to the "starter/frontend" folder

  # Test job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Ensure using the correct version
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v3  # Updated to v3
        with:
          path: starter/frontend/node_modules  # Adjusted path
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend  # Set working-directory to the "starter/frontend" folder

      - name: Run tests
        run: npm run test
        working-directory: ./starter/frontend  # Set working-directory to the "starter/frontend" folder

  # Build job, depends on lint and test jobs
  build:
    runs-on: ubuntu-latest
    needs: 
      - lint
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Ensure using the correct version
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v3  # Updated to v3
        with:
          path: starter/frontend/node_modules  # Adjusted path
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend  # Set working-directory to the "starter/frontend" folder

      - name: Build Docker image
        run: docker build -t frontend-app .
        working-directory: ./starter/frontend  # Set working-directory to the "starter/frontend" folder
