name: Frontend CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Lint job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ./starter/frontend/node_modules  # Path to node_modules in the starter/frontend directory
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}  # Cache key based on package-lock.json in starter/frontend

      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend  # Directory where package.json and package-lock.json are located

      - name: Run lint
        run: npm run lint
        working-directory: ./starter/frontend

  # Test job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v3  # Cache node_modules for the test step
        with:
          path: ./starter/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}  # Use package-lock.json in starter/frontend

      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend

      - name: Run tests
        run: npm run test
        working-directory: ./starter/frontend

  # Build job, depends on lint and test jobs
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ./starter/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}  # Cache based on package-lock.json in starter/frontend

      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend

      - name: Build Docker image
        run: docker build -t frontend-app .
        working-directory: ./starter/frontend
